ContactsManager.UI/Controllers/CountriesController.cs
using ContactsManager.Core.ServiceContracts;
using Microsoft.AspNetCore.Mvc;

namespace Contact_Manager.Controllers
{
    [Route("[controller]")]
    public class CountriesController : Controller
    {
        public readonly ICountriesService _countriesService;

        public CountriesController(ICountriesService countriesService)
        {
            _countriesService = countriesService;
        }

        [Route("UploadExcel")]
        [HttpGet]
        public IActionResult UploadExcel()
        {
            return View();
        }

        [Route("UploadExcel")]
        [HttpPost]
        public async Task<IActionResult> UploadExcel(IFormFile excelFile)
        {
            if (excelFile == null || excelFile.Length == 0)
            {
                ViewBag.ErrorMessage = "Please select an xlsx file";
                return View();
            }

            if (!Path.GetExtension(excelFile.FileName).Equals(".xlsx", StringComparison.OrdinalIgnoreCase))
            {
                ViewBag.ErrorMessage = "Unsupported fileType, Please select an xlsx file";
                return View();
            }
            
          int count = await _countriesService.UploadCountriesFromExcelFile(excelFile);

            ViewBag.Message = $"{count} Countries Uploaded";
            return View();
        }
    }
}

ContactsManager.UI/Views/Shared/_GridColumnHeader.cshtml
@* @{
    Console.WriteLine(ViewBag.CurrentSortBy);
    Console.WriteLine(ViewBag.ColumnName);
    Console.WriteLine(ViewBag.CurrentSortOrderOptions);
} *@
@if (ViewBag.CurrentSortBy == ViewBag.ColumnName && ViewBag.CurrentSortOrderOptions == SortOrderOptions.ASC.ToString())
{
    <th>
        <a href="~/persons/index?searchBy=@(ViewBag.CurrentSearchBy)&searchString=@(ViewBag.CurrentSearchString)&sortBy=@(ViewBag.ColumnName)&sortOrderOptions=@(nameof(SortOrderOptions.DESC))">
            @ViewBag.DisplayName
        </a>
        <i class="fa-solid fa-sort-up"></i>
    </th>
}
else if (ViewBag.CurrentSortBy == ViewBag.ColumnName && ViewBag.CurrentSortOrderOptions == SortOrderOptions.DESC.ToString())
{
    <th>
        <a href="~/persons/index?searchBy=@(ViewBag.CurrentSearchBy)&searchString=@(ViewBag.CurrentSearchString)&sortBy=@(ViewBag.ColumnName)&sortOrderOptions=@(nameof(SortOrderOptions.ASC))">
            @ViewBag.DisplayName
        </a>
        <i class="fa-solid fa-sort-down"></i>
    </th>
}
else
{
    <th>
        <a href="~/persons/index?searchBy=@(ViewBag.CurrentSearchBy)&searchString=@(ViewBag.CurrentSearchString)&sortBy=@(ViewBag.ColumnName)&sortOrderOptions=@(nameof(SortOrderOptions.ASC))">
            @ViewBag.DisplayName
        </a>
    </th>
}

ContactsManager.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @* <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" /> *@
    <link rel="stylesheet" href="~/StyleSheet.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="shortcut icon" href="~/favicon.ico" type="image/x-icon" />
    <link rel="icon" href="~/favicon.ico" type="image/x-icon" />


    <!-- Icons css -->
    <link href="~/css/icons.css" rel="stylesheet">

    <!--  bootstrap css-->
    <link href="~/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" />

    <!-- Data table css -->
    <link href="~/plugins/datatable/css/dataTables.bootstrap5.css" rel="stylesheet" />
    <link href="~/plugins/datatable/css/buttons.bootstrap5.min.css" rel="stylesheet">
    <link href="~/plugins/datatable/responsive.bootstrap5.css" rel="stylesheet" />

    <!--- Style css --->
    <link href="~/css/style.css" rel="stylesheet">
    <link href="~/css/style-dark.css" rel="stylesheet">
    <link href="~/css/style-transparent.css" rel="stylesheet">

    <!-- INTERNAL Select2 css -->
    <link href="~/plugins/select2/css/select2.min.css" rel="stylesheet" />

    <!---Skinmodes css-->
    <link href="~/css/skin-modes.css" rel="stylesheet" />

    <!--- Animations css-->
    <link href="~/css/animate.css" rel="stylesheet">
</head>

<body>
    <div class="container">
        <div class="page-content">

            <div class="margin-bottom w-100" >
                <div class="flex app-title" id="top-bar-div" style="border-bottom-left-radius:15px; border-bottom-right-radius:15px;">
                    <div class="flex-1" id="app-title-div">
                        <h1 >
                            @* <i class="fa-solid fa-people-simple"></i> *@
                            <img src="~/imageIcons/medium/images (3).png" alt="logo" style="height:50px; width:50px;" />
                            Contact Manager
                        </h1>
                    </div>


                    <div class="flex-1 pr" id="search-box-div">
                        <div class="navbar account-links" style="display:flex; float:right; align-items:center;">
                            @if (User.Identity.IsAuthenticated)
                            {
                                <ul class="m-0 p-0">
                                    <li class="lighttext1" style="font-family:'Segoe UI', Tahoma, Geneva, Verdana, sans-serif">
                                        <i class="fa-solid fa-user"></i>
                                        @User.Identity?.Name
                                    </li>
                                    @if (User.IsInRole("Admin"))
                                    {
                                        Console.WriteLine(User.IsInRole("User"));
                                        <li>
                                            <a asp-controller="Home" asp-action="Index" asp-area="Admin" class="lighttext1">Admin Home</a>
                                    </li>
                                    }
                                    <li>
                                        <a asp-controller="Auth" asp-action="Logout" class="lighttext1">Logout</a>
                                    </li>
                                </ul>
                            }
                            else
                            {

                                <ul class="m-0 p-0">
                                    @if (ViewBag.CurrentUrl == "~/Auth/Register")
                                    {
                                        <li>
                                            <a asp-controller="Auth" asp-action="Register" class="nav-active lighttext">Register</a>
                                        </li>
                                    }
                                    else
                                    {
                                        <li>
                                            <a asp-controller="Auth" asp-action="Register" class="lighttext">Register</a>
                                        </li>
                                    }

                                    @if (ViewBag.CurrentUrl == "~/Auth/Login")
                                    {
                                        <li>
                                            <a asp-controller="Auth" asp-action="Login" class="nav-active lighttext">Login</a>
                                        </li>
                                    }
                                    else
                                    {
                                        <li>
                                            <a asp-controller="Auth" asp-action="Login" class="lighttext">Login</a>
                                        </li>

                                    }
                                </ul>
                            }
                        </div>

                    </div>
                </div>

            </div>


            <div class="navbar mb">

                <ul style="padding-left:0px;">
                    <li>
                        @if (ViewBag.CurrentUrl == "~/Persons/Index")
                        {
                            <a asp-controller="Persons" asp-action="Index" class="nav-active">Persons</a>
                        }
                        else
                        {
                            <a asp-controller="Persons" asp-action="Index">Persons</a>
                        }
                        @if (ViewBag.CurrentUrl == "~/Movies/Index")
                        {
                            <a asp-controller="Movies" asp-action="Index" class="nav-active">Actors</a>
                        }
                        else
                        {
                            <a asp-controller="Movies" asp-action="Index">Actors</a>
                        }

                        @if (ViewBag.CurrentUrl == "~/Countries/UploadExcel")
                        {
                            <a asp-controller="Countries" asp-action="UploadExcel" class="nav-active">Upload Countries</a>
                        }
                        else
                        {
                            <a asp-controller="Countries" asp-action="UploadExcel">Upload Countries</a>
                        }

                        @if (ViewBag.CurrentUrl == "~/Persons/UploadExcel")
                        {
                            <a asp-controller="Persons" asp-action="UploadExcel" class="nav-active">Upload Persons</a>
                        }
                        else
                        {
                            <a asp-controller="Persons" asp-action="UploadExcel">Upload Persons</a>
                        }
                    </li>
                </ul>
            </div>

            <div class="body">
                @RenderBody()
            </div>
        </div>
    </div>

    <!-- JQuery min js -->
    <script src="~/plugins/jquery/jquery.min.js"></script>

    <!-- Bootstrap js -->
    <script src="~/plugins/bootstrap/js/popper.min.js"></script>
    <script src="~/plugins/bootstrap/js/bootstrap.min.js"></script>

    <!-- Ionicons js -->
    <script src="~/plugins/ionicons/ionicons.js"></script>

    <!-- Moment js -->
    <script src="~/plugins/moment/moment.js"></script>
@* 
    <!-- P-scroll js -->
    <script src="~/plugins/perfect-scrollbar/perfect-scrollbar.min.js"></script>
    <script src="~/plugins/perfect-scrollbar/p-scroll.js"></script> *@

    <!-- Internal Data tables -->
    <script src="~/plugins/datatable/js/jquery.dataTables.min.js"></script>
    <script src="~/plugins/datatable/js/dataTables.bootstrap5.js"></script>
    <script src="~/plugins/datatable/js/dataTables.buttons.min.js"></script>
    <script src="~/plugins/datatable/js/buttons.bootstrap5.min.js"></script>
    <script src="~/plugins/datatable/js/jszip.min.js"></script>
    <script src="~/plugins/datatable/pdfmake/pdfmake.min.js"></script>
    <script src="~/plugins/datatable/pdfmake/vfs_fonts.js"></script>
    <script src="~/plugins/datatable/js/buttons.html5.min.js"></script>
    <script src="~/plugins/datatable/js/buttons.print.min.js"></script>
    <script src="~/plugins/datatable/js/buttons.colVis.min.js"></script>
    <script src="~/plugins/datatable/dataTables.responsive.min.js"></script>
    <script src="~/plugins/datatable/responsive.bootstrap5.min.js"></script>
    <script src="~/js/table-data.js"></script>

    <!-- INTERNAL Select2 js -->
    <script src="~/plugins/select2/js/select2.full.min.js"></script>

    <!-- Sticky js -->
    <script src="~/js/sticky.js"></script>

    <!-- eva-icons js -->
    <script src="~/js/eva-icons.min.js"></script>

    <!-- Theme Color js -->
    <script src="~/js/themecolor.js"></script>

    <!-- custom js -->
    <script src="~/js/custom.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>